ls_qns = [
    "Is a Turbocharger and a Supercharger the same?",
    "What is the unit measurement of speed?",
    "What device in a car is used to reduce the noise produced by the exhaust?",
    "Which Car Manufacturer is the most successful in WRC",
    "Which Car Manufacturer craeted Carbotanium",
    "What part of the car transmits powerfrom the engine to the wheels?",
    "What is the car used in Back to the Future?",
    "Who has won the Singaporean Grand Prix the most in F1?",
    "What was the unique type of engine Mazda produced called?",
    "What brand does James Bond love?"
]

ls_ans = [
    "no",
    ["kilometre per hour","kmph","km/h", "miles per hour", "mph"],
    "muffler",
    "lancia",
    "pagani",
    ["transmission","gearbox"],
    "Delorean DMC-12",
    "sebastian vettel",
    "rotary engine",
    "aston martin"
]

ls_hint = [
    "",
    "Remember your math and physics lessons",
    "synonym for quiet",
    "Starts with L and reigns from Italy",
    "a guy that was sacked from Lamboghini",
    "transmit power",
    "DMC-12...",
    "He is a german",
    "Dorito",
    "A brand owned by a guy named Stroll"
]

ls_exp = [
    "A turbocharger uses the flow of exhaust gases, whereas a supercharger uses the rotation of the crankshaft",
    "Speed is how fast something is moving, so Distance / Time represents how far something goes in a certain amount of time",
    "A device for reducing the noise emitted by the exhaust of an internal combustion engine",
    "Lancia has won the WRC in 1974-1976, 1983, 1987-1992",
    "Horocio Pagani was sacked from Lamboghini, wanting to innovate Lamgohini's cars with the advancement of carbon fiber, which was ultimately rejected",
    "A transmission, or a gearbox, acts as the medium that transmits power generated by the engine to the wheels via a mechanical system of gears and gear train",
    "Director Robert Zemeckis and writer Robert Gale chose the 1981 DeLorean DMC-12 in part because the car's gullwing doors “made it look like an alien spaceship.”",
    "Sebastian Vettel won 5 times in Singapore",
    "The rotary engine was nicknamed a dorito due to the triangle spinning to produced power rather than using pistons",
    "Aston Martins have been a staple in James Bond movies, with the DB5 being the most iconic"
]

print("Welcome to Darryl's Quiz!!")

total_scoring = 0


def question_game(qn,ans,hint,expl):
    input_ans = input(qn+ " : ")
    if input_ans.lower() == ans or input_ans.lower() in ans:
         print("Correct!")
         global total_scoring
         total_scoring += 1
    else:
         print("Wrong!")

    print(expl)

playing = input("Do You Want To Play?[Y/N] ")

if playing == "N":
    quit
else:
     for num_qns in range(10):
          question_game(ls_qns[num_qns],ls_ans[num_qns],ls_hint[num_qns],ls_exp[num_qns])
    
print("Here is your total score: ") 
print(total_scoring)    
          



